"""
Step 10 — run the five required test questions against the assistant and write the full
transcript (question, retrieved chunks, answer, citations, validation result) to
TEST_RESULTS.md as well as printing it to the console.

Usage:
    python test_qa.py

Nothing about the expected answers is hard-coded; the script only records what the
pipeline actually returned. The one automated check is that the out-of-scope question
is answered with "I don't know" (Step 6) and that in-scope questions are not.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from qa_assistant import (
    EMBEDDING_MODEL_NAME,
    LLM_MODEL,
    TOP_K,
    AskResult,
    KnowledgeBase,
    _get_client,
    ask,
)

# (category, question)
TEST_QUESTIONS: list[tuple[str, str]] = [
    ("direct", "What percentage of the final grade is the final exam worth?"),
    ("direct", "When are Dr. Okafor's office hours?"),
    ("direct", "What is the penalty for submitting a programming assignment late?"),
    # Same fact as "Students must bring their university student ID card to every exam",
    # but phrased with different vocabulary to test semantic (not keyword) retrieval.
    ("synonym", "What kind of identification do I need to carry with me into a test?"),
    # Not covered anywhere in docs/ -> expected answer: "I don't know".
    ("not-in-docs", "How much does it cost to enrol in CS 201, and is there a tuition discount?"),
]

RESULTS_PATH = Path(__file__).parent / "TEST_RESULTS.md"


def result_to_markdown(n: int, category: str, r: AskResult) -> str:
    lines = [f"## Test {n} ({category})", "", f"**Question:** {r.question}", "", "**Retrieved chunks (top 4):**", ""]
    lines.append("| # | Source | Cosine | Snippet |")
    lines.append("|---|--------|--------|---------|")
    for i, rc in enumerate(r.retrieved, start=1):
        snippet = " ".join(rc.chunk.text.split())
        snippet = (snippet[:140] + "...") if len(snippet) > 140 else snippet
        snippet = snippet.replace("|", "\\|")
        lines.append(f"| [{i}] | `{rc.chunk.label}` | {rc.score:.3f} | {snippet} |")
    lines.append("")
    if r.response is None:
        lines.append("**Answer:** _no valid response after 1 retry_")
        if r.raw_llm_text:
            lines.append("")
            lines.append("Last raw model output:")
            lines.append("")
            lines.append("```")
            lines.append(r.raw_llm_text)
            lines.append("```")
    else:
        lines.append(f"**Answer:** {r.answer}")
        lines.append("")
        lines.append(f"**Citations:** {r.citations if r.citations else 'none'}")
        for num, rc in r.cited_chunks():
            lines.append(f"- [{num}] -> `{rc.chunk.label}`")
    lines.append("")
    lines.append(f"**Validation:** {'PASSED' if r.validation_passed else 'FAILED'}")
    lines.append("")
    lines.append("**Raw model JSON:**")
    lines.append("")
    lines.append("```json")
    lines.append(r.raw_llm_text or "(empty)")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("Building knowledge base ...", file=sys.stderr)
    kb = KnowledgeBase.build()
    client = _get_client()

    results: list[tuple[str, AskResult]] = []
    for category, question in TEST_QUESTIONS:
        r = ask(question, kb, client=client, verbose=True)
        results.append((category, r))
        print()

    # --- behavioural checks -------------------------------------------------------
    checks: list[tuple[str, bool]] = []
    for category, r in results:
        if category == "not-in-docs":
            checks.append((f'Out-of-scope question answered "I don\'t know": {r.question!r}', r.dont_know))
            checks.append(("Out-of-scope answer has no citations", r.citations == []))
        else:
            checks.append((f"In-scope question answered (not 'I don't know'): {r.question!r}", bool(r.response) and not r.dont_know))
            checks.append((f"In-scope answer cites at least one passage: {r.question!r}", len(r.citations) > 0))
        checks.append((f"Output validated against QAResponse: {r.question!r}", r.validation_passed))

    all_ok = all(ok for _, ok in checks)

    # --- write TEST_RESULTS.md ----------------------------------------------------
    md = [
        "# Test Results — Basic Document Q&A Assistant",
        "",
        f"Generated by `python test_qa.py` on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
        f"- Embedding model: `{EMBEDDING_MODEL_NAME}`",
        f"- LLM: `{LLM_MODEL}`",
        f"- Chunks indexed: {len(kb.chunks)} from {len({c.source for c in kb.chunks})} files in `docs/`",
        f"- Retrieval: top-{TOP_K} chunks by cosine similarity",
        "",
        "Citation numbers in each answer refer to the `[n]` rows of that test's retrieved-chunks table,",
        "so every citation can be traced to a source file and chunk index.",
        "",
        "## Summary",
        "",
        "| # | Category | Question | Validation | \"I don't know\"? | Citations |",
        "|---|----------|----------|------------|-----------------|-----------|",
    ]
    for i, (category, r) in enumerate(results, start=1):
        md.append(
            f"| {i} | {category} | {r.question} | {'PASSED' if r.validation_passed else 'FAILED'} | "
            f"{'yes' if r.dont_know else 'no'} | {r.citations if r.citations else 'none'} |"
        )
    md += ["", "## Behavioural checks", ""]
    for label, ok in checks:
        md.append(f"- {'PASS' if ok else 'FAIL'} — {label}")
    md += ["", f"**Overall: {'ALL CHECKS PASSED' if all_ok else 'SOME CHECKS FAILED'}**", "", "---", ""]
    for i, (category, r) in enumerate(results, start=1):
        md.append(result_to_markdown(i, category, r))
        md.append("---")
        md.append("")

    RESULTS_PATH.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote {RESULTS_PATH}", file=sys.stderr)

    print("\nBehavioural checks:")
    for label, ok in checks:
        print(f"  {'PASS' if ok else 'FAIL'}  {label}")
    print(f"\nOverall: {'ALL CHECKS PASSED' if all_ok else 'SOME CHECKS FAILED'}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
